package com.og.health.sleeptracker.schema;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "WAKE_UP".
 */
public class WakeUp {

    private Long id;
    private java.util.Date wakeUpTime;

    public WakeUp() {
    }

    public WakeUp(Long id) {
        this.id = id;
    }

    public WakeUp(Long id, java.util.Date wakeUpTime) {
        this.id = id;
        this.wakeUpTime = wakeUpTime;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public java.util.Date getWakeUpTime() {
        return wakeUpTime;
    }

    public void setWakeUpTime(java.util.Date wakeUpTime) {
        this.wakeUpTime = wakeUpTime;
    }

}
